name: TEST
on:
  workflow_dispatch:
env:
  NODE_VERSION: '14.15'
jobs:

  deploy-docker:
    name: "Checkout test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git branch --contains "v0.12.0-dev22"
      - run: git branch --contains "v0.12.0-dev22" | wc -l
      - run: git branch
      - run: git pull --all
      - run: git branch